# Generated by Django 5.1.4 on 2024-12-19 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('is_dir', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_dir', 'file_name'],
                'managed': False,
            },
        ),
    ]
