# Generated by Django 5.1.4 on 2024-12-19 07:10

from django.db import migrations

from client.models import BinaryExtension
from .data.extensions import extensions

def create_binary_extensions(apps, schema_editor):
        # BinaryExtension = apps.get_model('client', 'BinaryExtension')
        for extension in extensions:
            BinaryExtension.objects.update_or_create(extension=extension)
    
def remove_binary_extensions(apps, schema_editor):
        # BinaryExtension = apps.get_model('client', 'BinaryExtension')
        BinaryExtension.objects.filter(extension__in=extensions).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_binary_extensions, remove_binary_extensions),
    ]
