# Generated by Django 5.1.4 on 2024-12-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_add_protocols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
