# Generated by Django 5.1.4 on 2024-12-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_alter_connection_password_alter_connection_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
